//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gofra.ServiceExceptionHandler {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemBase", Namespace="http://schemas.datacontract.org/2004/07/LIB.Tools.BO")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.User))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.Graphic))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.Person))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.Sex))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.Person1))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.AggregateBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.BugState))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.PredefinedColor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.Role))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.ModelBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.PrintBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.Bug))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.Developer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.Project))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.ProjectState))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.ProjectType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.StatusCode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.Ticket))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.Install))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.Client))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.ProductOwner))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.ServerInstalled))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.Priority))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.TicketState))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.RequestType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.Excep))]
    public partial class ItemBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string Categoryk__BackingFieldField;
        
        private Gofra.ServiceExceptionHandler.User CreatedByk__BackingFieldField;
        
        private System.DateTime DateCreatedk__BackingFieldField;
        
        private Gofra.ServiceExceptionHandler.User DeletedByk__BackingFieldField;
        
        private long Idk__BackingFieldField;
        
        private System.Collections.Generic.Dictionary<long, Gofra.ServiceExceptionHandler.ItemBase> SearchItemsk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Category>k__BackingField", IsRequired=true)]
        public string Categoryk__BackingField {
            get {
                return this.Categoryk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Categoryk__BackingFieldField, value) != true)) {
                    this.Categoryk__BackingFieldField = value;
                    this.RaisePropertyChanged("Categoryk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CreatedBy>k__BackingField", IsRequired=true)]
        public Gofra.ServiceExceptionHandler.User CreatedByk__BackingField {
            get {
                return this.CreatedByk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByk__BackingFieldField, value) != true)) {
                    this.CreatedByk__BackingFieldField = value;
                    this.RaisePropertyChanged("CreatedByk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DateCreated>k__BackingField", IsRequired=true)]
        public System.DateTime DateCreatedk__BackingField {
            get {
                return this.DateCreatedk__BackingFieldField;
            }
            set {
                if ((this.DateCreatedk__BackingFieldField.Equals(value) != true)) {
                    this.DateCreatedk__BackingFieldField = value;
                    this.RaisePropertyChanged("DateCreatedk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DeletedBy>k__BackingField", IsRequired=true)]
        public Gofra.ServiceExceptionHandler.User DeletedByk__BackingField {
            get {
                return this.DeletedByk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.DeletedByk__BackingFieldField, value) != true)) {
                    this.DeletedByk__BackingFieldField = value;
                    this.RaisePropertyChanged("DeletedByk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Id>k__BackingField", IsRequired=true)]
        public long Idk__BackingField {
            get {
                return this.Idk__BackingFieldField;
            }
            set {
                if ((this.Idk__BackingFieldField.Equals(value) != true)) {
                    this.Idk__BackingFieldField = value;
                    this.RaisePropertyChanged("Idk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<SearchItems>k__BackingField", IsRequired=true)]
        public System.Collections.Generic.Dictionary<long, Gofra.ServiceExceptionHandler.ItemBase> SearchItemsk__BackingField {
            get {
                return this.SearchItemsk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.SearchItemsk__BackingFieldField, value) != true)) {
                    this.SearchItemsk__BackingFieldField = value;
                    this.RaisePropertyChanged("SearchItemsk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/LIB.BusinessObjects")]
    [System.SerializableAttribute()]
    public partial class User : Gofra.ServiceExceptionHandler.ItemBase {
        
        private Gofra.ServiceExceptionHandler.Graphic _ImageField;
        
        private bool DisplayErrork__BackingFieldField;
        
        private bool Enabledk__BackingFieldField;
        
        private System.DateTime LastLogink__BackingFieldField;
        
        private string Logink__BackingFieldField;
        
        private string Passwordk__BackingFieldField;
        
        private long Permissionk__BackingFieldField;
        
        private Gofra.ServiceExceptionHandler.Person Personk__BackingFieldField;
        
        private Gofra.ServiceExceptionHandler.Role Rolek__BackingFieldField;
        
        private int Timeoutk__BackingFieldField;
        
        private System.Guid UniqueIdk__BackingFieldField;
        
        private Gofra.ServiceExceptionHandler.User UpdatedByk__BackingFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Gofra.ServiceExceptionHandler.Graphic _Image {
            get {
                return this._ImageField;
            }
            set {
                if ((object.ReferenceEquals(this._ImageField, value) != true)) {
                    this._ImageField = value;
                    this.RaisePropertyChanged("_Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DisplayError>k__BackingField", IsRequired=true)]
        public bool DisplayErrork__BackingField {
            get {
                return this.DisplayErrork__BackingFieldField;
            }
            set {
                if ((this.DisplayErrork__BackingFieldField.Equals(value) != true)) {
                    this.DisplayErrork__BackingFieldField = value;
                    this.RaisePropertyChanged("DisplayErrork__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Enabled>k__BackingField", IsRequired=true)]
        public bool Enabledk__BackingField {
            get {
                return this.Enabledk__BackingFieldField;
            }
            set {
                if ((this.Enabledk__BackingFieldField.Equals(value) != true)) {
                    this.Enabledk__BackingFieldField = value;
                    this.RaisePropertyChanged("Enabledk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<LastLogin>k__BackingField", IsRequired=true)]
        public System.DateTime LastLogink__BackingField {
            get {
                return this.LastLogink__BackingFieldField;
            }
            set {
                if ((this.LastLogink__BackingFieldField.Equals(value) != true)) {
                    this.LastLogink__BackingFieldField = value;
                    this.RaisePropertyChanged("LastLogink__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Login>k__BackingField", IsRequired=true)]
        public string Logink__BackingField {
            get {
                return this.Logink__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Logink__BackingFieldField, value) != true)) {
                    this.Logink__BackingFieldField = value;
                    this.RaisePropertyChanged("Logink__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Password>k__BackingField", IsRequired=true)]
        public string Passwordk__BackingField {
            get {
                return this.Passwordk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Passwordk__BackingFieldField, value) != true)) {
                    this.Passwordk__BackingFieldField = value;
                    this.RaisePropertyChanged("Passwordk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Permission>k__BackingField", IsRequired=true)]
        public long Permissionk__BackingField {
            get {
                return this.Permissionk__BackingFieldField;
            }
            set {
                if ((this.Permissionk__BackingFieldField.Equals(value) != true)) {
                    this.Permissionk__BackingFieldField = value;
                    this.RaisePropertyChanged("Permissionk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Person>k__BackingField", IsRequired=true)]
        public Gofra.ServiceExceptionHandler.Person Personk__BackingField {
            get {
                return this.Personk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Personk__BackingFieldField, value) != true)) {
                    this.Personk__BackingFieldField = value;
                    this.RaisePropertyChanged("Personk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Role>k__BackingField", IsRequired=true)]
        public Gofra.ServiceExceptionHandler.Role Rolek__BackingField {
            get {
                return this.Rolek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Rolek__BackingFieldField, value) != true)) {
                    this.Rolek__BackingFieldField = value;
                    this.RaisePropertyChanged("Rolek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Timeout>k__BackingField", IsRequired=true)]
        public int Timeoutk__BackingField {
            get {
                return this.Timeoutk__BackingFieldField;
            }
            set {
                if ((this.Timeoutk__BackingFieldField.Equals(value) != true)) {
                    this.Timeoutk__BackingFieldField = value;
                    this.RaisePropertyChanged("Timeoutk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<UniqueId>k__BackingField", IsRequired=true)]
        public System.Guid UniqueIdk__BackingField {
            get {
                return this.UniqueIdk__BackingFieldField;
            }
            set {
                if ((this.UniqueIdk__BackingFieldField.Equals(value) != true)) {
                    this.UniqueIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("UniqueIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<UpdatedBy>k__BackingField", IsRequired=true)]
        public Gofra.ServiceExceptionHandler.User UpdatedByk__BackingField {
            get {
                return this.UpdatedByk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedByk__BackingFieldField, value) != true)) {
                    this.UpdatedByk__BackingFieldField = value;
                    this.RaisePropertyChanged("UpdatedByk__BackingField");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Graphic", Namespace="http://schemas.datacontract.org/2004/07/LIB.BusinessObjects")]
    [System.SerializableAttribute()]
    public partial class Graphic : Gofra.ServiceExceptionHandler.ItemBase {
        
        private string BONamek__BackingFieldField;
        
        private string Extk__BackingFieldField;
        
        private string Namek__BackingFieldField;
        
        private string _RelativePathk__BackingFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<BOName>k__BackingField", IsRequired=true)]
        public string BONamek__BackingField {
            get {
                return this.BONamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.BONamek__BackingFieldField, value) != true)) {
                    this.BONamek__BackingFieldField = value;
                    this.RaisePropertyChanged("BONamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Ext>k__BackingField", IsRequired=true)]
        public string Extk__BackingField {
            get {
                return this.Extk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Extk__BackingFieldField, value) != true)) {
                    this.Extk__BackingFieldField = value;
                    this.RaisePropertyChanged("Extk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Name>k__BackingField", IsRequired=true)]
        public string Namek__BackingField {
            get {
                return this.Namek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Namek__BackingFieldField, value) != true)) {
                    this.Namek__BackingFieldField = value;
                    this.RaisePropertyChanged("Namek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<_RelativePath>k__BackingField", IsRequired=true)]
        public string _RelativePathk__BackingField {
            get {
                return this._RelativePathk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this._RelativePathk__BackingFieldField, value) != true)) {
                    this._RelativePathk__BackingFieldField = value;
                    this.RaisePropertyChanged("_RelativePathk__BackingField");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/LIB.BusinessObjects")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.Person1))]
    public partial class Person : Gofra.ServiceExceptionHandler.ItemBase {
        
        private string Emailk__BackingFieldField;
        
        private string FirstNamek__BackingFieldField;
        
        private string LastNamek__BackingFieldField;
        
        private Gofra.ServiceExceptionHandler.Sex Sexk__BackingFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Email>k__BackingField", IsRequired=true)]
        public string Emailk__BackingField {
            get {
                return this.Emailk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Emailk__BackingFieldField, value) != true)) {
                    this.Emailk__BackingFieldField = value;
                    this.RaisePropertyChanged("Emailk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<FirstName>k__BackingField", IsRequired=true)]
        public string FirstNamek__BackingField {
            get {
                return this.FirstNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNamek__BackingFieldField, value) != true)) {
                    this.FirstNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("FirstNamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<LastName>k__BackingField", IsRequired=true)]
        public string LastNamek__BackingField {
            get {
                return this.LastNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNamek__BackingFieldField, value) != true)) {
                    this.LastNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("LastNamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Sex>k__BackingField", IsRequired=true)]
        public Gofra.ServiceExceptionHandler.Sex Sexk__BackingField {
            get {
                return this.Sexk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Sexk__BackingFieldField, value) != true)) {
                    this.Sexk__BackingFieldField = value;
                    this.RaisePropertyChanged("Sexk__BackingField");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sex", Namespace="http://schemas.datacontract.org/2004/07/LIB.BusinessObjects")]
    [System.SerializableAttribute()]
    public partial class Sex : Gofra.ServiceExceptionHandler.ItemBase {
        
        private string Namek__BackingFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Name>k__BackingField", IsRequired=true)]
        public string Namek__BackingField {
            get {
                return this.Namek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Namek__BackingFieldField, value) != true)) {
                    this.Namek__BackingFieldField = value;
                    this.RaisePropertyChanged("Namek__BackingField");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/ER_BTLib.BusinessObjects")]
    [System.SerializableAttribute()]
    public partial class Person1 : Gofra.ServiceExceptionHandler.Person {
        
        private string Phonek__BackingFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Phone>k__BackingField", IsRequired=true)]
        public string Phonek__BackingField {
            get {
                return this.Phonek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Phonek__BackingFieldField, value) != true)) {
                    this.Phonek__BackingFieldField = value;
                    this.RaisePropertyChanged("Phonek__BackingField");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AggregateBase", Namespace="http://schemas.datacontract.org/2004/07/LIB.Tools.BO")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.BugState))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.Role))]
    public partial class AggregateBase : Gofra.ServiceExceptionHandler.ItemBase {
        
        private string Colork__BackingFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Color>k__BackingField", IsRequired=true)]
        public string Colork__BackingField {
            get {
                return this.Colork__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Colork__BackingFieldField, value) != true)) {
                    this.Colork__BackingFieldField = value;
                    this.RaisePropertyChanged("Colork__BackingField");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BugState", Namespace="http://schemas.datacontract.org/2004/07/ER_BT.Models.Objects")]
    [System.SerializableAttribute()]
    public partial class BugState : Gofra.ServiceExceptionHandler.AggregateBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gofra.ServiceExceptionHandler.PredefinedColor PredefinedColorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gofra.ServiceExceptionHandler.PredefinedColor PredefinedColor {
            get {
                return this.PredefinedColorField;
            }
            set {
                if ((object.ReferenceEquals(this.PredefinedColorField, value) != true)) {
                    this.PredefinedColorField = value;
                    this.RaisePropertyChanged("PredefinedColor");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PredefinedColor", Namespace="http://schemas.datacontract.org/2004/07/LIB.BusinessObjects")]
    [System.SerializableAttribute()]
    public partial class PredefinedColor : Gofra.ServiceExceptionHandler.ItemBase {
        
        private string Codek__BackingFieldField;
        
        private string Colork__BackingFieldField;
        
        private string Namek__BackingFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Code>k__BackingField", IsRequired=true)]
        public string Codek__BackingField {
            get {
                return this.Codek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Codek__BackingFieldField, value) != true)) {
                    this.Codek__BackingFieldField = value;
                    this.RaisePropertyChanged("Codek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Color>k__BackingField", IsRequired=true)]
        public string Colork__BackingField {
            get {
                return this.Colork__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Colork__BackingFieldField, value) != true)) {
                    this.Colork__BackingFieldField = value;
                    this.RaisePropertyChanged("Colork__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Name>k__BackingField", IsRequired=true)]
        public string Namek__BackingField {
            get {
                return this.Namek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Namek__BackingFieldField, value) != true)) {
                    this.Namek__BackingFieldField = value;
                    this.RaisePropertyChanged("Namek__BackingField");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Role", Namespace="http://schemas.datacontract.org/2004/07/LIB.BusinessObjects")]
    [System.SerializableAttribute()]
    public partial class Role : Gofra.ServiceExceptionHandler.AggregateBase {
        
        private Gofra.ServiceExceptionHandler.Graphic Avatark__BackingFieldField;
        
        private string Namek__BackingFieldField;
        
        private long Permissionk__BackingFieldField;
        
        private long RoleAccessPermissionk__BackingFieldField;
        
        private int UserCountk__BackingFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Avatar>k__BackingField", IsRequired=true)]
        public Gofra.ServiceExceptionHandler.Graphic Avatark__BackingField {
            get {
                return this.Avatark__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Avatark__BackingFieldField, value) != true)) {
                    this.Avatark__BackingFieldField = value;
                    this.RaisePropertyChanged("Avatark__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Name>k__BackingField", IsRequired=true)]
        public string Namek__BackingField {
            get {
                return this.Namek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Namek__BackingFieldField, value) != true)) {
                    this.Namek__BackingFieldField = value;
                    this.RaisePropertyChanged("Namek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Permission>k__BackingField", IsRequired=true)]
        public long Permissionk__BackingField {
            get {
                return this.Permissionk__BackingFieldField;
            }
            set {
                if ((this.Permissionk__BackingFieldField.Equals(value) != true)) {
                    this.Permissionk__BackingFieldField = value;
                    this.RaisePropertyChanged("Permissionk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<RoleAccessPermission>k__BackingField", IsRequired=true)]
        public long RoleAccessPermissionk__BackingField {
            get {
                return this.RoleAccessPermissionk__BackingFieldField;
            }
            set {
                if ((this.RoleAccessPermissionk__BackingFieldField.Equals(value) != true)) {
                    this.RoleAccessPermissionk__BackingFieldField = value;
                    this.RaisePropertyChanged("RoleAccessPermissionk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<UserCount>k__BackingField", IsRequired=true)]
        public int UserCountk__BackingField {
            get {
                return this.UserCountk__BackingFieldField;
            }
            set {
                if ((this.UserCountk__BackingFieldField.Equals(value) != true)) {
                    this.UserCountk__BackingFieldField = value;
                    this.RaisePropertyChanged("UserCountk__BackingField");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModelBase", Namespace="http://schemas.datacontract.org/2004/07/ER_BTLib.BusinessObjects")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.PrintBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.Bug))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.Developer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.Project))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.ProjectState))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.ProjectType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.StatusCode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.Ticket))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.Install))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.Client))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.ProductOwner))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.ServerInstalled))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.Priority))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.TicketState))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.RequestType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.Excep))]
    public partial class ModelBase : Gofra.ServiceExceptionHandler.ItemBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrintBase", Namespace="http://schemas.datacontract.org/2004/07/ER_BTLib.BusinessObjects")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.Bug))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.Developer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.Project))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.ProjectState))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.ProjectType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.StatusCode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.Ticket))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.Install))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.Client))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.ProductOwner))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.ServerInstalled))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.Priority))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.TicketState))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.RequestType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gofra.ServiceExceptionHandler.Excep))]
    public partial class PrintBase : Gofra.ServiceExceptionHandler.ModelBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileDownloadNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> FiltersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrintTemplateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StylesFileField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileDownloadName {
            get {
                return this.FileDownloadNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileDownloadNameField, value) != true)) {
                    this.FileDownloadNameField = value;
                    this.RaisePropertyChanged("FileDownloadName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> Filters {
            get {
                return this.FiltersField;
            }
            set {
                if ((object.ReferenceEquals(this.FiltersField, value) != true)) {
                    this.FiltersField = value;
                    this.RaisePropertyChanged("Filters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrintTemplate {
            get {
                return this.PrintTemplateField;
            }
            set {
                if ((object.ReferenceEquals(this.PrintTemplateField, value) != true)) {
                    this.PrintTemplateField = value;
                    this.RaisePropertyChanged("PrintTemplate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StylesFile {
            get {
                return this.StylesFileField;
            }
            set {
                if ((object.ReferenceEquals(this.StylesFileField, value) != true)) {
                    this.StylesFileField = value;
                    this.RaisePropertyChanged("StylesFile");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bug", Namespace="http://schemas.datacontract.org/2004/07/ER_BT.Models.Objects")]
    [System.SerializableAttribute()]
    public partial class Bug : Gofra.ServiceExceptionHandler.PrintBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BugIgnoredCommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gofra.ServiceExceptionHandler.BugState BugStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gofra.ServiceExceptionHandler.Developer DeveloperField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gofra.ServiceExceptionHandler.Project ProjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResolutionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SearchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gofra.ServiceExceptionHandler.StatusCode StatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gofra.ServiceExceptionHandler.Ticket TicketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BugIgnoredComment {
            get {
                return this.BugIgnoredCommentField;
            }
            set {
                if ((object.ReferenceEquals(this.BugIgnoredCommentField, value) != true)) {
                    this.BugIgnoredCommentField = value;
                    this.RaisePropertyChanged("BugIgnoredComment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gofra.ServiceExceptionHandler.BugState BugState {
            get {
                return this.BugStateField;
            }
            set {
                if ((object.ReferenceEquals(this.BugStateField, value) != true)) {
                    this.BugStateField = value;
                    this.RaisePropertyChanged("BugState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gofra.ServiceExceptionHandler.Developer Developer {
            get {
                return this.DeveloperField;
            }
            set {
                if ((object.ReferenceEquals(this.DeveloperField, value) != true)) {
                    this.DeveloperField = value;
                    this.RaisePropertyChanged("Developer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gofra.ServiceExceptionHandler.Project Project {
            get {
                return this.ProjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectField, value) != true)) {
                    this.ProjectField = value;
                    this.RaisePropertyChanged("Project");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Resolution {
            get {
                return this.ResolutionField;
            }
            set {
                if ((object.ReferenceEquals(this.ResolutionField, value) != true)) {
                    this.ResolutionField = value;
                    this.RaisePropertyChanged("Resolution");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Search {
            get {
                return this.SearchField;
            }
            set {
                if ((this.SearchField.Equals(value) != true)) {
                    this.SearchField = value;
                    this.RaisePropertyChanged("Search");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gofra.ServiceExceptionHandler.StatusCode StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusCodeField, value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gofra.ServiceExceptionHandler.Ticket Ticket {
            get {
                return this.TicketField;
            }
            set {
                if ((object.ReferenceEquals(this.TicketField, value) != true)) {
                    this.TicketField = value;
                    this.RaisePropertyChanged("Ticket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Developer", Namespace="http://schemas.datacontract.org/2004/07/ER_BT.Models.Objects")]
    [System.SerializableAttribute()]
    public partial class Developer : Gofra.ServiceExceptionHandler.PrintBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gofra.ServiceExceptionHandler.Person1 PersonField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gofra.ServiceExceptionHandler.Person1 Person {
            get {
                return this.PersonField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonField, value) != true)) {
                    this.PersonField = value;
                    this.RaisePropertyChanged("Person");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Project", Namespace="http://schemas.datacontract.org/2004/07/ER_BT.Models.Objects")]
    [System.SerializableAttribute()]
    public partial class Project : Gofra.ServiceExceptionHandler.PrintBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BugCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<long, Gofra.ServiceExceptionHandler.ItemBase> BugsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<long, Gofra.ServiceExceptionHandler.ItemBase> InstallsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gofra.ServiceExceptionHandler.ProjectState ProjectStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gofra.ServiceExceptionHandler.ProjectType ProjectTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<long, Gofra.ServiceExceptionHandler.ItemBase> TechnologyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BugCount {
            get {
                return this.BugCountField;
            }
            set {
                if ((this.BugCountField.Equals(value) != true)) {
                    this.BugCountField = value;
                    this.RaisePropertyChanged("BugCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<long, Gofra.ServiceExceptionHandler.ItemBase> Bugs {
            get {
                return this.BugsField;
            }
            set {
                if ((object.ReferenceEquals(this.BugsField, value) != true)) {
                    this.BugsField = value;
                    this.RaisePropertyChanged("Bugs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<long, Gofra.ServiceExceptionHandler.ItemBase> Installs {
            get {
                return this.InstallsField;
            }
            set {
                if ((object.ReferenceEquals(this.InstallsField, value) != true)) {
                    this.InstallsField = value;
                    this.RaisePropertyChanged("Installs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gofra.ServiceExceptionHandler.ProjectState ProjectState {
            get {
                return this.ProjectStateField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectStateField, value) != true)) {
                    this.ProjectStateField = value;
                    this.RaisePropertyChanged("ProjectState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gofra.ServiceExceptionHandler.ProjectType ProjectType {
            get {
                return this.ProjectTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectTypeField, value) != true)) {
                    this.ProjectTypeField = value;
                    this.RaisePropertyChanged("ProjectType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<long, Gofra.ServiceExceptionHandler.ItemBase> Technology {
            get {
                return this.TechnologyField;
            }
            set {
                if ((object.ReferenceEquals(this.TechnologyField, value) != true)) {
                    this.TechnologyField = value;
                    this.RaisePropertyChanged("Technology");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProjectState", Namespace="http://schemas.datacontract.org/2004/07/ER_BT.Models.Objects")]
    [System.SerializableAttribute()]
    public partial class ProjectState : Gofra.ServiceExceptionHandler.PrintBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProjectType", Namespace="http://schemas.datacontract.org/2004/07/ER_BT.Models.Objects")]
    [System.SerializableAttribute()]
    public partial class ProjectType : Gofra.ServiceExceptionHandler.PrintBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusCode", Namespace="http://schemas.datacontract.org/2004/07/ER_BT.Models.Objects")]
    [System.SerializableAttribute()]
    public partial class StatusCode : Gofra.ServiceExceptionHandler.PrintBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ticket", Namespace="http://schemas.datacontract.org/2004/07/ER_BT.Models.Objects")]
    [System.SerializableAttribute()]
    public partial class Ticket : Gofra.ServiceExceptionHandler.PrintBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gofra.ServiceExceptionHandler.Install InstallField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<long, Gofra.ServiceExceptionHandler.ItemBase> InstallsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gofra.ServiceExceptionHandler.Priority PriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gofra.ServiceExceptionHandler.ProductOwner ProductOwnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gofra.ServiceExceptionHandler.Project ProjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<long, Gofra.ServiceExceptionHandler.ItemBase> ProjectsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResolutionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gofra.ServiceExceptionHandler.TicketState TicketStateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gofra.ServiceExceptionHandler.Install Install {
            get {
                return this.InstallField;
            }
            set {
                if ((object.ReferenceEquals(this.InstallField, value) != true)) {
                    this.InstallField = value;
                    this.RaisePropertyChanged("Install");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<long, Gofra.ServiceExceptionHandler.ItemBase> Installs {
            get {
                return this.InstallsField;
            }
            set {
                if ((object.ReferenceEquals(this.InstallsField, value) != true)) {
                    this.InstallsField = value;
                    this.RaisePropertyChanged("Installs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gofra.ServiceExceptionHandler.Priority Priority {
            get {
                return this.PriorityField;
            }
            set {
                if ((object.ReferenceEquals(this.PriorityField, value) != true)) {
                    this.PriorityField = value;
                    this.RaisePropertyChanged("Priority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gofra.ServiceExceptionHandler.ProductOwner ProductOwner {
            get {
                return this.ProductOwnerField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductOwnerField, value) != true)) {
                    this.ProductOwnerField = value;
                    this.RaisePropertyChanged("ProductOwner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gofra.ServiceExceptionHandler.Project Project {
            get {
                return this.ProjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectField, value) != true)) {
                    this.ProjectField = value;
                    this.RaisePropertyChanged("Project");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<long, Gofra.ServiceExceptionHandler.ItemBase> Projects {
            get {
                return this.ProjectsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectsField, value) != true)) {
                    this.ProjectsField = value;
                    this.RaisePropertyChanged("Projects");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Resolution {
            get {
                return this.ResolutionField;
            }
            set {
                if ((object.ReferenceEquals(this.ResolutionField, value) != true)) {
                    this.ResolutionField = value;
                    this.RaisePropertyChanged("Resolution");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gofra.ServiceExceptionHandler.TicketState TicketState {
            get {
                return this.TicketStateField;
            }
            set {
                if ((object.ReferenceEquals(this.TicketStateField, value) != true)) {
                    this.TicketStateField = value;
                    this.RaisePropertyChanged("TicketState");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Install", Namespace="http://schemas.datacontract.org/2004/07/ER_BT.Models.Objects")]
    [System.SerializableAttribute()]
    public partial class Install : Gofra.ServiceExceptionHandler.PrintBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BugCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gofra.ServiceExceptionHandler.Client ClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateInstalledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<long, Gofra.ServiceExceptionHandler.ItemBase> ExcepsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstallKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gofra.ServiceExceptionHandler.ProductOwner ProductOwnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductOwnerListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gofra.ServiceExceptionHandler.Project ProjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gofra.ServiceExceptionHandler.ServerInstalled ServerInstalledField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BugCount {
            get {
                return this.BugCountField;
            }
            set {
                if ((this.BugCountField.Equals(value) != true)) {
                    this.BugCountField = value;
                    this.RaisePropertyChanged("BugCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gofra.ServiceExceptionHandler.Client Client {
            get {
                return this.ClientField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientField, value) != true)) {
                    this.ClientField = value;
                    this.RaisePropertyChanged("Client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientList {
            get {
                return this.ClientListField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientListField, value) != true)) {
                    this.ClientListField = value;
                    this.RaisePropertyChanged("ClientList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateInstalled {
            get {
                return this.DateInstalledField;
            }
            set {
                if ((this.DateInstalledField.Equals(value) != true)) {
                    this.DateInstalledField = value;
                    this.RaisePropertyChanged("DateInstalled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<long, Gofra.ServiceExceptionHandler.ItemBase> Exceps {
            get {
                return this.ExcepsField;
            }
            set {
                if ((object.ReferenceEquals(this.ExcepsField, value) != true)) {
                    this.ExcepsField = value;
                    this.RaisePropertyChanged("Exceps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstallKey {
            get {
                return this.InstallKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.InstallKeyField, value) != true)) {
                    this.InstallKeyField = value;
                    this.RaisePropertyChanged("InstallKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gofra.ServiceExceptionHandler.ProductOwner ProductOwner {
            get {
                return this.ProductOwnerField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductOwnerField, value) != true)) {
                    this.ProductOwnerField = value;
                    this.RaisePropertyChanged("ProductOwner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductOwnerList {
            get {
                return this.ProductOwnerListField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductOwnerListField, value) != true)) {
                    this.ProductOwnerListField = value;
                    this.RaisePropertyChanged("ProductOwnerList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gofra.ServiceExceptionHandler.Project Project {
            get {
                return this.ProjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectField, value) != true)) {
                    this.ProjectField = value;
                    this.RaisePropertyChanged("Project");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gofra.ServiceExceptionHandler.ServerInstalled ServerInstalled {
            get {
                return this.ServerInstalledField;
            }
            set {
                if ((object.ReferenceEquals(this.ServerInstalledField, value) != true)) {
                    this.ServerInstalledField = value;
                    this.RaisePropertyChanged("ServerInstalled");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/ER_BT.Models.Objects")]
    [System.SerializableAttribute()]
    public partial class Client : Gofra.ServiceExceptionHandler.PrintBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gofra.ServiceExceptionHandler.Person1 PersonField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gofra.ServiceExceptionHandler.Person1 Person {
            get {
                return this.PersonField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonField, value) != true)) {
                    this.PersonField = value;
                    this.RaisePropertyChanged("Person");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductOwner", Namespace="http://schemas.datacontract.org/2004/07/ER_BT.Models.Objects")]
    [System.SerializableAttribute()]
    public partial class ProductOwner : Gofra.ServiceExceptionHandler.PrintBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gofra.ServiceExceptionHandler.Person1 PersonField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gofra.ServiceExceptionHandler.Person1 Person {
            get {
                return this.PersonField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonField, value) != true)) {
                    this.PersonField = value;
                    this.RaisePropertyChanged("Person");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServerInstalled", Namespace="http://schemas.datacontract.org/2004/07/ER_BT.Models.Objects")]
    [System.SerializableAttribute()]
    public partial class ServerInstalled : Gofra.ServiceExceptionHandler.PrintBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Priority", Namespace="http://schemas.datacontract.org/2004/07/ER_BT.Models.Objects")]
    [System.SerializableAttribute()]
    public partial class Priority : Gofra.ServiceExceptionHandler.PrintBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TicketState", Namespace="http://schemas.datacontract.org/2004/07/ER_BT.Models.Objects")]
    [System.SerializableAttribute()]
    public partial class TicketState : Gofra.ServiceExceptionHandler.PrintBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gofra.ServiceExceptionHandler.PredefinedColor PredefinedColorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gofra.ServiceExceptionHandler.PredefinedColor PredefinedColor {
            get {
                return this.PredefinedColorField;
            }
            set {
                if ((object.ReferenceEquals(this.PredefinedColorField, value) != true)) {
                    this.PredefinedColorField = value;
                    this.RaisePropertyChanged("PredefinedColor");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestType", Namespace="http://schemas.datacontract.org/2004/07/ER_BT.Models.Objects")]
    [System.SerializableAttribute()]
    public partial class RequestType : Gofra.ServiceExceptionHandler.PrintBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Excep", Namespace="http://schemas.datacontract.org/2004/07/ER_BT.Models.Objects")]
    [System.SerializableAttribute()]
    public partial class Excep : Gofra.ServiceExceptionHandler.PrintBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gofra.ServiceExceptionHandler.Bug BugField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gofra.ServiceExceptionHandler.Install InstallField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QueryStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gofra.ServiceExceptionHandler.RequestType RequestTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gofra.ServiceExceptionHandler.StatusCode StatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlReferrerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserAgentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserHostAdressField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gofra.ServiceExceptionHandler.Bug Bug {
            get {
                return this.BugField;
            }
            set {
                if ((object.ReferenceEquals(this.BugField, value) != true)) {
                    this.BugField = value;
                    this.RaisePropertyChanged("Bug");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gofra.ServiceExceptionHandler.Install Install {
            get {
                return this.InstallField;
            }
            set {
                if ((object.ReferenceEquals(this.InstallField, value) != true)) {
                    this.InstallField = value;
                    this.RaisePropertyChanged("Install");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Post {
            get {
                return this.PostField;
            }
            set {
                if ((object.ReferenceEquals(this.PostField, value) != true)) {
                    this.PostField = value;
                    this.RaisePropertyChanged("Post");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QueryString {
            get {
                return this.QueryStringField;
            }
            set {
                if ((object.ReferenceEquals(this.QueryStringField, value) != true)) {
                    this.QueryStringField = value;
                    this.RaisePropertyChanged("QueryString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gofra.ServiceExceptionHandler.RequestType RequestType {
            get {
                return this.RequestTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestTypeField, value) != true)) {
                    this.RequestTypeField = value;
                    this.RaisePropertyChanged("RequestType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gofra.ServiceExceptionHandler.StatusCode StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusCodeField, value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrlReferrer {
            get {
                return this.UrlReferrerField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlReferrerField, value) != true)) {
                    this.UrlReferrerField = value;
                    this.RaisePropertyChanged("UrlReferrer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserAgent {
            get {
                return this.UserAgentField;
            }
            set {
                if ((object.ReferenceEquals(this.UserAgentField, value) != true)) {
                    this.UserAgentField = value;
                    this.RaisePropertyChanged("UserAgent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserHostAdress {
            get {
                return this.UserHostAdressField;
            }
            set {
                if ((object.ReferenceEquals(this.UserHostAdressField, value) != true)) {
                    this.UserHostAdressField = value;
                    this.RaisePropertyChanged("UserHostAdress");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceExceptionHandler.IExceptionService")]
    public interface IExceptionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExceptionService/SaveException", ReplyAction="http://tempuri.org/IExceptionService/SaveExceptionResponse")]
        void SaveException(Gofra.ServiceExceptionHandler.Excep exception, string installKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExceptionService/SaveException", ReplyAction="http://tempuri.org/IExceptionService/SaveExceptionResponse")]
        System.Threading.Tasks.Task SaveExceptionAsync(Gofra.ServiceExceptionHandler.Excep exception, string installKey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExceptionServiceChannel : Gofra.ServiceExceptionHandler.IExceptionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExceptionServiceClient : System.ServiceModel.ClientBase<Gofra.ServiceExceptionHandler.IExceptionService>, Gofra.ServiceExceptionHandler.IExceptionService {
        
        public ExceptionServiceClient() {
        }
        
        public ExceptionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExceptionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExceptionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExceptionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SaveException(Gofra.ServiceExceptionHandler.Excep exception, string installKey) {
            base.Channel.SaveException(exception, installKey);
        }
        
        public System.Threading.Tasks.Task SaveExceptionAsync(Gofra.ServiceExceptionHandler.Excep exception, string installKey) {
            return base.Channel.SaveExceptionAsync(exception, installKey);
        }
    }
}
